### ISSUE TITLE
[BUG] ValueError: X has 31 features, but StandardScaler is expecting 19 features as input.

### ISSUE THREAD

**Issue by jamc1996** [wfondrie/mokapot#42]
Hi,

Thanks for your work on mokapot!

I'm trying to use it in one of my pipelines at the moment but I'm facing the error shown below when I run it on a dataset which works with percolator without any error,

The traceback is shown below, from the stdoutt it seems to occur after the first training iteration is complete.
```
Traceback (most recent call last):
.../mokapot/mokapot.py", line 95, in main
    datasets, model=model, test_fdr=config.test_fdr, folds=config.folds
.../mokapot/brew.py", line 115, in brew
    _predict(p, i, models, test_fdr) for p, i in zip(psms, test_idx)
.../mokapot/brew.py", line 115, in <listcomp>
    _predict(p, i, models, test_fdr) for p, i in zip(psms, test_idx)
.../mokapot/brew.py", line 221, in _predict
    test_set._calibrate_scores(mod.predict(test_set), test_fdr)
.../mokapot/model.py", line 232, in predict
    return self.decision_function(psms)
.../mokapot/model.py", line 225, in decision_function
    psms.features.loc[:, self.features].values
.../sklearn/preprocessing/_data.py", line 980, in transform
    force_all_finite="allow-nan",
.../sklearn/base.py", line 580, in _validate_data
    self._check_n_features(X, reset=reset)
../sklearn/base.py", line 396, in _check_n_features
    f"X has {n_features} features, but {self.__class__.__name__} "
ValueError: X has 31 features, but StandardScaler is expecting 19 features as input.
```

**Comment by jamc1996** [comment]
Oh and in case it's relevant since it's complaining about number of features, my dataset has 17 features - 22 total columns.

**Comment by wfondrie** [comment]
Thanks for reaching out @jamc1996. Can you also post your full command and logging messages?

**Comment by jamc1996** [comment]
Ahhh shoot sorry I woke up this morning and realised it was my own fault, I had a duplicate column name in my data...I'm guessing percolator only looks at column index whereas mokapot uses column names?

When I drop the change the column name everything runs as expected.

Thanks for the quick response and apologies for raising a bug without checking everything first.

**Comment by wfondrie** [comment]
No problem at all. 

> I'm guessing percolator only looks at column index whereas mokapot uses column names?

That is correct. There is upsides and downsides to both design choices as you found out. I like using names, just in case folks have the same features but in a different order. 

If you have any questions, feel free to use the discussion board. Also, please don't hesitate to report any potential bugs you come across!
