### ISSUE TITLE
[BUG] Different scores for LinearConfidence and GroupConfidence

### ISSUE THREAD

**Issue by bittremieux** [wfondrie/mokapot#64]
`LinearConfidence` and `GroupedConfidence` give different scores, even when for `GroupedConfidence` all PSMs are part of a single group. I'm using a random forest, which should give scores between 0 and 1, but for `GroupedConfidence` the scores seem to range between 1 and 2 instead.

When using `LinearConfidence`:
```
import mokapot
from sklearn.ensemble import RandomForestClassifier
psms = mokapot.read_pin("phospho_rep1.pin")
moka_conf, _ = mokapot.brew(psms, mokapot.Model(RandomForestClassifier(random_state=1)))
moka_conf.psms["mokapot score"].describe()
```
Output:
```
count    42330.000000
mean         0.686944
std          0.435288
min          0.000000
25%          0.060000
50%          1.000000
75%          1.000000
max          1.000000
```

For simplicity, I use the constant `Charge1` column in the example PIN file as group for `GroupedConfidence`, i.e. all PSMs are part of the same group (`Charge1 == 0`):
```
import mokapot
from sklearn.ensemble import RandomForestClassifier
psms_grouped = mokapot.read_pin("phospho_rep1.pin", group_column="Charge1")
moka_conf_grouped, _ = mokapot.brew(psms_grouped, mokapot.Model(RandomForestClassifier(random_state=1)))
moka_conf_grouped.group_confidence_estimates[0].psms["mokapot score"].describe()
```

Output:
```
count    42330.000000
mean         1.687226
std          0.435448
min          1.000000
25%          1.060000
50%          2.000000
75%          2.000000
max          2.000000
```

Note how the scores seem to be almost identical except for being 1 more. I tried to figure out in the code what was happening, but didn't immediately find the problem.

This is with mokapot version 0.8.2.

**Comment by wfondrie** [comment]
Well that is strange indeed! I'll check it out.

**Comment by wfondrie** [comment]
I think I've found the problem. Just adding a test now and I should get a PR up tonight or tomorrow.
