### ISSUE TITLE
[Upgrade] Migrate to full pyproject.toml build

### ISSUE THREAD

**Issue by wfondrie** [wfondrie/mokapot#66]
With Setuptools >=61, the full package specification can be made in `pyproject.toml`, eliminating the need for `setup.cfg` and `setup.py`.

**Comment by jspaezp** [comment]
check out https://github.com/wfondrie/mokapot/pull/77 :)

**Comment by jspaezp** [comment]
I think this can be closed now :)

**Comment by wfondrie** [comment]
haha thanks!
